[build]
  command = "npm run build:netlify"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"
  # Required for Docker build
  NETLIFY_USE_YARN = "false"
  NETLIFY_IMAGE_INCLUDED_PATHS = "/*"

# Increase function timeouts for video processing
[functions]
  node_bundler = "esbuild"
  included_files = ["**/*.wasm"]

[functions."api/*"]
  included_files = ["**/*.wasm", "node_modules/@ffmpeg/core/**"]
  node_bundler = "esbuild"
  external_node_modules = ["@ffmpeg/ffmpeg", "@ffmpeg/util"]
  
[functions."api/generateVideo/*"]
  timeout = 300
  memory = 3008

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Docker configuration for local development
[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3000
  publish = ".next"
  framework = "nextjs" 