[build]
  command = "npm run netlify:build"
  publish = ".next"

[build.environment]
  NODE_ENV = "development"
  NETLIFY = "true"
  FFMPEG_PATH = "/usr/bin/ffmpeg"
  FONT_PATH = "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"
  FFMPEG_FONT_PATH = "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"
  FONTCONFIG_PATH = "/etc/fonts"
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"

# Create an environment variable alias for FFMPEG_PATH
[context.production.environment]
  NETLIFY_FFMPEG_PATH = "/usr/bin/ffmpeg"

# Increase function timeouts for video processing
[functions]
  node_bundler = "esbuild"
  included_files = ["**/*.wasm", ".netlify/bin/**"]

[functions."api/*"]
  included_files = ["**/*.wasm", "node_modules/@ffmpeg/core/**"]
  node_bundler = "esbuild"
  external_node_modules = ["@ffmpeg/ffmpeg", "@ffmpeg/util"]
  
[functions."api/generateVideo/*"]
  timeout = 300
  memory = 3008

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Run a pre-install script to install FFmpeg before the build
[build.lifecycle]
  onInit = "apt-get update && apt-get install -y ffmpeg fontconfig fonts-dejavu"

# This redirects all requests to the Next.js application
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next"
  status = 200 