[build]
  command = "node scripts/netlify-post-install.js && npm run build && node scripts/fix-netlify-functions.js"
  publish = ".next"
  ignore = "git diff --quiet HEAD^ HEAD ./app/"

[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"
  NETLIFY_USE_PNPM = "false"

# Create an environment variable alias for FFMPEG_PATH
[context.production.environment]
  NETLIFY_FFMPEG_PATH = ".netlify/bin/ffmpeg"

# Increase function timeouts for video processing
[functions]
  node_bundler = "esbuild"
  included_files = ["**/*.wasm", ".netlify/bin/**"]

[functions."api/*"]
  included_files = ["**/*.wasm", "node_modules/@ffmpeg/core/**", ".netlify/bin/**"]
  node_bundler = "esbuild"
  external_node_modules = ["@ffmpeg/ffmpeg", "@ffmpeg/util"]
  
[functions."api/generateVideo/*"]
  timeout = 300
  memory = 3008
  included_files = [".netlify/bin/**"]

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Docker configuration for local development
[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3000
  publish = ".next"
  framework = "nextjs" 