# Use Netlify Docker Beta feature
[build]
  base = "."
  publish = ".next" 
  command = "echo 'Building with Docker'"
  
# Create the .next directory so Netlify can find it
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Use beta Docker features
[build.environment]
  NETLIFY_USE_DOCKER = "true"
  DOCKER_FILE = "Dockerfile.netlify"
  NODE_VERSION = "18"

# This redirects all requests to the Next.js application
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next"
  status = 200 