[build]
  command = "npm run build"
  publish = ".next"
  ignore = "git diff --quiet HEAD^ HEAD ./app/"

[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"
  NETLIFY_USE_PNPM = "false"

# Create an environment variable alias for FFMPEG_PATH
[context.production.environment]
  NETLIFY_FFMPEG_PATH = "/usr/bin/ffmpeg"

# Increase function timeouts for video processing
[functions]
  node_bundler = "esbuild"
  included_files = ["**/*.wasm", ".netlify/bin/**"]

[functions."api/*"]
  included_files = ["**/*.wasm", "node_modules/@ffmpeg/core/**"]
  node_bundler = "esbuild"
  external_node_modules = ["@ffmpeg/ffmpeg", "@ffmpeg/util"]
  
[functions."api/generateVideo/*"]
  timeout = 300
  memory = 3008

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Specify Docker container for build and functions
[build.image]
  command = "npm run build"
  publish = ".next"
  base = "node:18-bullseye"
  packages = ["ffmpeg"]

# Docker configuration for local development
[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3000
  publish = ".next"
  framework = "nextjs" 