name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Heroku Container Registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login

      - name: Build and push Docker image
        env:
          HEROKU_APP_NAME: "lockinalpha"
        run: |
          heroku container:push web --app $HEROKU_APP_NAME

      - name: Release the image
        env:
          HEROKU_APP_NAME: "lockinalpha"
        run: |
          heroku container:release web --app $HEROKU_APP_NAME
